name: UnitTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install modules
      run: yarn
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
      with:
        jestArgs: path/to/my.test.js
