name: UnitTest

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install modules
        run: yarn
    # - name: Run Jest
    # run: yarn test
